export default {
  login: "aadhar41",
  id: 22677832,
  node_id: "MDQ6VXNlcjIyNjc3ODMy",
  avatar_url: "https://avatars.githubusercontent.com/u/22677832?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/aadhar41",
  html_url: "https://github.com/aadhar41",
  followers_url: "https://api.github.com/users/aadhar41/followers",
  following_url: "https://api.github.com/users/aadhar41/following{/other_user}",
  gists_url: "https://api.github.com/users/aadhar41/gists{/gist_id}",
  starred_url: "https://api.github.com/users/aadhar41/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/aadhar41/subscriptions",
  organizations_url: "https://api.github.com/users/aadhar41/orgs",
  repos_url: "https://api.github.com/users/aadhar41/repos",
  events_url: "https://api.github.com/users/aadhar41/events{/privacy}",
  received_events_url: "https://api.github.com/users/aadhar41/received_events",
  type: "User",
  user_view_type: "public",
  site_admin: false,
  name: "Aadhar Gaur",
  company: "Freelancer",
  blog: "https://aadhar-gaur-cx4uwli.gamma.site/",
  location: "Jaipur",
  email: null,
  hireable: true,
  bio: "SENIOR SOFTWARE ENGINEER | WEB DEVELOPER | PHP | LARAVEL | YII | JAVASCRIPT | MERN",
  twitter_username: "aadhar_gaur",
  public_repos: 150,
  public_gists: 6,
  followers: 5,
  following: 31,
  created_at: "2016-10-07T09:35:19Z",
  updated_at: "2026-02-20T08:16:02Z"
};
