export default [
  {
    login: "vignesh9782",
    id: 40609760,
    node_id: "MDQ6VXNlcjQwNjA5NzYw",
    avatar_url: "https://avatars.githubusercontent.com/u/40609760?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/vignesh9782",
    html_url: "https://github.com/vignesh9782",
    followers_url: "https://api.github.com/users/vignesh9782/followers",
    following_url: "https://api.github.com/users/vignesh9782/following{/other_user}",
    gists_url: "https://api.github.com/users/vignesh9782/gists{/gist_id}",
    starred_url: "https://api.github.com/users/vignesh9782/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/vignesh9782/subscriptions",
    organizations_url: "https://api.github.com/users/vignesh9782/orgs",
    repos_url: "https://api.github.com/users/vignesh9782/repos",
    events_url: "https://api.github.com/users/vignesh9782/events{/privacy}",
    received_events_url: "https://api.github.com/users/vignesh9782/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false
  },
  {
    login: "nholuongut",
    id: 58627821,
    node_id: "MDQ6VXNlcjU4NjI3ODIx",
    avatar_url: "https://avatars.githubusercontent.com/u/58627821?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/nholuongut",
    html_url: "https://github.com/nholuongut",
    followers_url: "https://api.github.com/users/nholuongut/followers",
    following_url: "https://api.github.com/users/nholuongut/following{/other_user}",
    gists_url: "https://api.github.com/users/nholuongut/gists{/gist_id}",
    starred_url: "https://api.github.com/users/nholuongut/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/nholuongut/subscriptions",
    organizations_url: "https://api.github.com/users/nholuongut/orgs",
    repos_url: "https://api.github.com/users/nholuongut/repos",
    events_url: "https://api.github.com/users/nholuongut/events{/privacy}",
    received_events_url: "https://api.github.com/users/nholuongut/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false
  },
  {
    login: "Alihamza3864",
    id: 84718430,
    node_id: "MDQ6VXNlcjg0NzE4NDMw",
    avatar_url: "https://avatars.githubusercontent.com/u/84718430?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Alihamza3864",
    html_url: "https://github.com/Alihamza3864",
    followers_url: "https://api.github.com/users/Alihamza3864/followers",
    following_url: "https://api.github.com/users/Alihamza3864/following{/other_user}",
    gists_url: "https://api.github.com/users/Alihamza3864/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Alihamza3864/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Alihamza3864/subscriptions",
    organizations_url: "https://api.github.com/users/Alihamza3864/orgs",
    repos_url: "https://api.github.com/users/Alihamza3864/repos",
    events_url: "https://api.github.com/users/Alihamza3864/events{/privacy}",
    received_events_url: "https://api.github.com/users/Alihamza3864/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false
  },
  {
    login: "seckinyasar",
    id: 86570205,
    node_id: "MDQ6VXNlcjg2NTcwMjA1",
    avatar_url: "https://avatars.githubusercontent.com/u/86570205?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/seckinyasar",
    html_url: "https://github.com/seckinyasar",
    followers_url: "https://api.github.com/users/seckinyasar/followers",
    following_url: "https://api.github.com/users/seckinyasar/following{/other_user}",
    gists_url: "https://api.github.com/users/seckinyasar/gists{/gist_id}",
    starred_url: "https://api.github.com/users/seckinyasar/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/seckinyasar/subscriptions",
    organizations_url: "https://api.github.com/users/seckinyasar/orgs",
    repos_url: "https://api.github.com/users/seckinyasar/repos",
    events_url: "https://api.github.com/users/seckinyasar/events{/privacy}",
    received_events_url: "https://api.github.com/users/seckinyasar/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false
  },
  {
    login: "S4IL21",
    id: 126200245,
    node_id: "U_kgDOB4WptQ",
    avatar_url: "https://avatars.githubusercontent.com/u/126200245?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/S4IL21",
    html_url: "https://github.com/S4IL21",
    followers_url: "https://api.github.com/users/S4IL21/followers",
    following_url: "https://api.github.com/users/S4IL21/following{/other_user}",
    gists_url: "https://api.github.com/users/S4IL21/gists{/gist_id}",
    starred_url: "https://api.github.com/users/S4IL21/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/S4IL21/subscriptions",
    organizations_url: "https://api.github.com/users/S4IL21/orgs",
    repos_url: "https://api.github.com/users/S4IL21/repos",
    events_url: "https://api.github.com/users/S4IL21/events{/privacy}",
    received_events_url: "https://api.github.com/users/S4IL21/received_events",
    type: "User",
    user_view_type: "public",
    site_admin: false
  }
];
